import { Product } from "@/types";

export const products: Product[] = [
  {
    id: 1,
    name: "Wireless Noise-Cancelling Headphones",
    price: 249.99,
    originalPrice: 329.99,
    rating: 4.8,
    reviewCount: 1243,
    image: "https://m.media-amazon.com/images/I/61RahTQtAqL._AC_UF894,1000_QL80_.jpg",
    category: "Electronics",
    badge: "sale",
    description: "Premium over-ear headphones with 30-hour battery life and adaptive noise cancellation.",
  },
  {
    id: 2,
    name: "Minimalist Leather Watch",
    price: 189.00,
    rating: 4.7,
    reviewCount: 856,
    image: "https://m.media-amazon.com/images/I/61RahTQtAqL._AC_UF894,1000_QL80_.jpg",
    category: "Accessories",
    badge: "featured",
    description: "Slim profile watch with genuine leather strap and sapphire crystal glass.",
  },
  {
    id: 3,
    name: "Ultralight Running Sneakers",
    price: 129.95,
    originalPrice: 159.95,
    rating: 4.6,
    reviewCount: 2104,
    image: "https://content.woolovers.com/img/747x856/6b39d-46431_k3m_navy_m_11.jpg",
    category: "Footwear",
    badge: "sale",
    description: "Breathable mesh upper with responsive foam midsole for all-day comfort.",
  },
  {
    id: 4,
    name: "Portable Bluetooth Speaker",
    price: 79.99,
    rating: 4.5,
    reviewCount: 678,
    image: "https://cdn.thewirecutter.com/wp-content/media/2024/11/portablebluetoothspeakers-2048px-9130.jpg?width=2048&quality=60&crop=2048:1365&auto=webp",
    category: "Electronics",
    badge: "new",
    description: "360° surround sound with 12-hour playtime and IPX7 waterproof rating.",
  },
  {
    id: 5,
    name: "Merino Wool Crewneck Sweater",
    price: 95.00,
    rating: 4.9,
    reviewCount: 432,
    image: "https://content.woolovers.com/img/747x856/6b39d-46431_k3m_navy_m_11.jpg",
    category: "Clothing",
    badge: "bestseller",
    description: "Ethically sourced merino wool, naturally temperature-regulating and ultra-soft.",
  },
  {
    id: 6,
    name: "Stainless Steel Water Bottle",
    price: 34.99,
    rating: 4.7,
    reviewCount: 3201,
    image: "http://www.gymreapers.com/cdn/shop/files/32-oz-bottle-pink-with-caps.jpg?v=1714666627&width=2048",
    category: "Lifestyle",
    description: "Double-wall vacuum insulation keeps drinks cold 24h or hot 12h.",
  },
  {
    id: 7,
    name: "Smart Fitness Tracker Band",
    price: 59.99,
    originalPrice: 89.99,
    rating: 4.4,
    reviewCount: 1567,
    image: "https://m.media-amazon.com/images/I/71KwGt+7qSL._AC_UF894,1000_QL80_.jpg",
    category: "Electronics",
    badge: "sale",
    description: "Tracks heart rate, sleep, steps, and calories with a 7-day battery life.",
  },
  {
    id: 8,
    name: "Canvas Tote Bag",
    price: 42.00,
    rating: 4.6,
    reviewCount: 289,
    image: "https://www.burpee.com/media/catalog/product/1/9/19789a25e426e46273feefd29bcbbe3b0c75b13649816990db64183236e48eff.jpeg?optimize=medium&bg-color=255,255,255&fit=bounds&height=680&width=680",
    category: "Accessories",
    badge: "new",
    description: "Heavy-duty organic cotton canvas with reinforced handles and interior pocket.",
  },
  {
    id: 9,
    name: "Polarized Aviator Sunglasses",
    price: 115.00,
    originalPrice: 145.00,
    rating: 4.5,
    reviewCount: 743,
    image: "https://shady-rays.s3.us-east-2.amazonaws.com/assets/ascend/AV-23SN/02.jpg",
    category: "Accessories",
    badge: "sale",
    description: "UV400 polarized lenses with lightweight titanium frame for all-day wear.",
  },
  {
    id: 10,
    name: "Slim Fit Chino Pants",
    price: 68.00,
    rating: 4.3,
    reviewCount: 921,
    image: "https://www.roddandgunn.com/on/demandware.static/-/Sites-roddandgunn-master-catalog/default/dwc913ca7e/images/007173/VP0611_PEBBLE_FT_LGE.jpg",
    category: "Clothing",
    description: "Stretch-cotton blend for a tailored look with all-day flexibility.",
  },
  {
    id: 11,
    name: "Ceramic Pour-Over Coffee Set",
    price: 54.99,
    rating: 4.8,
    reviewCount: 512,
    image: "https://m.media-amazon.com/images/I/7159+ELcEOL._AC_UF894,1000_QL80_.jpg",
    category: "Lifestyle",
    badge: "featured",
    description: "Hand-crafted ceramic dripper with matching carafe and reusable filter.",
  },
  {
    id: 12,
    name: "Leather Bifold Wallet",
    price: 49.00,
    rating: 4.7,
    reviewCount: 1089,
    image: "https://www.holtzleather.com/cdn/shop/files/the-slim-dixie-fine-leather-bifold-wallet-7963564_2048x.jpg?v=1762812686",
    category: "Accessories",
    description: "Full-grain leather with RFID blocking and 8 card slots.",
  },
  {
    id: 13,
    name: "Yoga Mat with Alignment Lines",
    price: 45.00,
    originalPrice: 60.00,
    rating: 4.6,
    reviewCount: 834,
    image: "https://cdn.shopify.com/s/files/1/0868/4453/9204/files/TPE_Alignment_Mat_Image_02v2_480x480.jpg?v=1737458389",
    category: "Lifestyle",
    badge: "sale",
    description: "Non-slip natural rubber base with printed alignment guides for perfect form.",
  },
  {
    id: 14,
    name: "Graphic Print T-Shirt",
    price: 29.99,
    rating: 4.4,
    reviewCount: 1456,
    image: "https://i.etsystatic.com/6153077/r/il/38298a/2003165418/il_570xN.2003165418_czzs.jpg",
    category: "Clothing",
    badge: "new",
    description: "100% organic cotton with water-based ink print that won't crack or fade.",
  },
  {
    id: 15,
    name: "Mechanical Keyboard TKL",
    price: 139.00,
    rating: 4.9,
    reviewCount: 678,
    image: "https://media.gamestop.com/i/gamestop/20006080_Black_ALT02?$pdp$?w=1256&h=664&fmt=auto",
    category: "Electronics",
    badge: "bestseller",
    description: "Tenkeyless layout with hot-swappable switches and per-key RGB lighting.",
  },
  {
    id: 16,
    name: "Ankle Chelsea Boots",
    price: 159.00,
    originalPrice: 199.00,
    rating: 4.5,
    reviewCount: 367,
    image: "https://i5.walmartimages.com/seo/HARVEST-LAND-Women-Chelsea-Boots-Black-Ankle-Boots-Fashion-Soft-Flat-Booties-for-Female-Size-6_e1a39082-9780-4e86-96c7-c78256478caa.e45850b9c7656d3d583d8d82d6c98fd9.jpeg",
    category: "Footwear",
    badge: "sale",
    description: "Genuine leather upper with elastic side panels and stacked heel.",
  },
];

export const categories = ["All", "Electronics", "Clothing", "Accessories", "Footwear", "Lifestyle"];
